# Generated by Django 6.0.2 on 2026-03-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About', 'verbose_name_plural': 'About us'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AddField(
            model_name='aboutus',
            name='info_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Information'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='info_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Information'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='name_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='profession_en',
            field=models.CharField(max_length=64, null=True, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='profession_uz',
            field=models.CharField(max_length=64, null=True, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_en',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_uz',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='contact',
            name='full_name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='contact',
            name='full_name_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='contact',
            name='message_en',
            field=models.TextField(null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='contact',
            name='message_uz',
            field=models.TextField(null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='info',
            field=models.CharField(max_length=255, verbose_name='Information'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='profession',
            field=models.CharField(max_length=64, verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='full_name',
            field=models.CharField(max_length=128, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_read',
            field=models.BooleanField(default=True, verbose_name='Is read'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
