# Generated by Django 6.0.2 on 2026-03-05 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Product category', 'verbose_name_plural': 'Product categories'},
        ),
        migrations.AlterModelOptions(
            name='productcolor',
            options={'verbose_name': 'Product color', 'verbose_name_plural': 'Product colors'},
        ),
        migrations.AlterModelOptions(
            name='productcolorquantity',
            options={'verbose_name': 'Product color quantity', 'verbose_name_plural': 'Product color quantities'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order'], 'verbose_name': 'Product image', 'verbose_name_plural': 'Product images'},
        ),
        migrations.AlterModelOptions(
            name='producttag',
            options={'verbose_name': 'Product tag', 'verbose_name_plural': 'Product tags'},
        ),
        migrations.AddField(
            model_name='manufacture',
            name='country_en',
            field=models.CharField(blank=True, help_text='Country of origin', max_length=128, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='manufacture',
            name='country_uz',
            field=models.CharField(blank=True, help_text='Country of origin', max_length=128, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='manufacture',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='manufacture',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='manufacture',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='manufacture',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_uz',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='name_en',
            field=models.CharField(help_text='e.g. Walnut Brown, Oak Natural', max_length=64, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='name_uz',
            field=models.CharField(help_text='e.g. Walnut Brown, Oak Natural', max_length=64, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='producttag',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='producttag',
            name='name_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price_rub',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount price (RUB)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount price (USD)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price_uzs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount price (UZS)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product_images/', verbose_name='Main image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_rub',
            field=models.DecimalField(decimal_places=2, help_text='Price in Russian ruble', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price (RUB)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, help_text='Price in US dollar', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price (USD)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_uzs',
            field=models.DecimalField(decimal_places=2, help_text='Price in Uzbek sum', max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price (UZS)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('OUT_OF_STOCK', 'Out of stock'), ('DISCONTINUED', 'Discontinued'), ('COMING_SOON', 'Coming soon')], default='AVAILABLE', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='hex_code',
            field=models.CharField(help_text='e.g. #8B4513', max_length=7, verbose_name='HEX code'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='productcolorquantity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='productcolorquantity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
